### ISSUE TITLE
Improve performance of tearing out a window

### ISSUE THREAD

**Issue by owennw** [ScottLogic/bitflux-openfin#321]
Currently there is quite a lag between dropping the torn out card and seeing the new window.

If the overhead is from creating a new OF window (it may not be this), then this could be mitigated by keeping a pool of unused OF windows and managing that.

If it's the startup of a new app then I'm not sure how to improve that.

**Comment by WPFerg** [comment]
I think it's creating a new OF window, tearouts are windows and they're fine when cached. Do you explicitly show the window after everything's loaded?

**Comment by owennw** [comment]
The window gets shown on the success callback of the OF method `new fin.desktop.Window()`, which is out of my control. I assume that gets triggered once the window has been created and populated with the supplied URL.

**Comment by WPFerg** [comment]
So long as it's not waiting for angular to initialise, keeping a pool should be okay then

**Comment by owennw** [comment]
Closed by #341
