### ISSUE TITLE
expand an asset on double click in compact view

### ISSUE THREAD

**Issue by akhmorgan** [ScottLogic/bitflux-openfin#351]

**Comment by owennw** [comment]
What's the exact idea for this?

**Comment by akhmorgan** [comment]
It was brought up in a meeting a while ago. The general idea is that if a user double clicks on a favourite whilst in compact view, that favourite will be selected and the window will expand to the full view showing the graph for that stock.

**Comment by owennw** [comment]
Closed by #397
