### ISSUE TITLE
Finalise the project name!

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/bitflux-openfin#417]
Do we want to keep the bitflux name?

**Comment by akhmorgan** [comment]
StockFlux?

**Comment by owennw** [comment]
Given we're not using bitcoin I think the 'bit' bit would be out of place.

**Comment by ColinEberhardt** [comment]
StockFlux sounds good to me - and at least gives the name a relationship of sorts with bit flux

**Comment by owennw** [comment]
@ColinEberhardt Is that the final name then? If so we can begin renaming windows etc.

**Comment by ColinEberhardt** [comment]
Yeah, let's go with StockFlux
