### ISSUE TITLE
Improve the release process

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/bitflux-openfin#424]
We need to know:
 - [x] When a user reports an issue, which version it relates to
 - [x] Provide documentation of the install process (where is it installed to?)

**Comment by owennw** [comment]
Interestingly, because of the way we're hosting that app at the moment, there's only one version a user can use. What is our plan for hosting the app for a release?

**Comment by ColinEberhardt** [comment]
I think github pages is fine for release.

Even though a user can only see one version, it would make sense to track the version that a bug was reported against. Something like help -> about (but less ugly!)

**Comment by WPFerg** [comment]
@ColinEberhardt Where should the install process documentation go? `README.md`?

**Comment by ColinEberhardt** [comment]
@WPFerg yeah, README makes sense.

I think the outline of this file should be roughly as follows:

- A very brief overview of what this project is in just a few sentences, maybe a screenshot
- End-user documentation, i.e. installation instructions
- Developer documentation (the current README contents, although the use of `--target` needs to be included!)

**Comment by WPFerg** [comment]
Re `target`: #448, but I'll add screenshots/installation instructions :smile:

**Comment by WPFerg** [comment]
#453 and #443 solve this.
