### ISSUE TITLE
Should we allow selection of search results?

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/bitflux-openfin#430]
I can search for a stock, then select it rather than favourite it, then close the search pane. This leads to the application being in a somewhat inconsistent state - where none of the favourite stocks are selected.

**Comment by owennw** [comment]
Why is that inconsistent? There is a text label above the chart that displays the currently selected stock.

**Comment by ColinEberhardt** [comment]
Good point @owennw we'll keep the current behaviour.

**Comment by owennw** [comment]
It could be that the label isn't obvious enough though! It's hard for me to tell given I've been using the app a lot.
