### ISSUE TITLE
You can tear out windows so that they are off screen

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/bitflux-openfin#434]
- [x] If you take a tile, and drag it to the bottom right of your desktop, the new window appears entirely off screen.

- [x] i don't think the new windows should appear with it's top left corner at the mouse location - it should be offset.

**Comment by WPFerg** [comment]
For part 2, it might be easiest to just offset the created window by fixed `x, y`. The user's mouse is always going to be within a small rectangle when (where the tearout image is).

You can't track the mouse `x, y` relative to the window when beginning a tearout and use that. If you're tearing out the third favourite, the offset would put the mouse where the third favourite is. This also doesn't take into account scrolling

**Comment by WPFerg** [comment]
Closed by #439 and #446
