### ISSUE TITLE
tear-out should not require you to drag outside of the window

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/bitflux-openfin#435]
Currently you have to drag a tile until it is entirely outside of the windows bounds. I think it should tear out as soon as you drag beyond the favourites pane bounds (possibly plus a small tolerance).

i.e. copy Chrome ;-)

**Comment by owennw** [comment]
Would this also be the behaviour for tear in? I.e. the card will only tear in when intersected with a favourites pane.

**Comment by owennw** [comment]
Closed by #440
