### ISSUE TITLE
Can't tear out card into different monitor

### ISSUE THREAD

**Issue by owennw** [ScottLogic/bitflux-openfin#447]
When I try and tear out a card onto a different monitor it is moved back to my primary monitor immediately, sometimes in an unhelpful position!

**Comment by WPFerg** [comment]
If you revert d178fc6, do you still have the error?

**Comment by owennw** [comment]
No.

**Comment by WPFerg** [comment]
It'll be worth doing that, then. I could only access one taskbar, so I'm not sure how else it can be done

**Comment by WPFerg** [comment]
This issue's been fixed, however taskbar consideration is a nice-to-have, so I'm going to create a new issue for this specifically.
